package net.minestom.server.instance.block.sound;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface SoundTypes {
    SoundType WOOD = SoundTypeImpl.get("WOOD");

    SoundType GRAVEL = SoundTypeImpl.get("GRAVEL");

    SoundType GRASS = SoundTypeImpl.get("GRASS");

    SoundType LILY_PAD = SoundTypeImpl.get("LILY_PAD");

    SoundType STONE = SoundTypeImpl.get("STONE");

    SoundType METAL = SoundTypeImpl.get("METAL");

    SoundType GLASS = SoundTypeImpl.get("GLASS");

    SoundType WOOL = SoundTypeImpl.get("WOOL");

    SoundType SAND = SoundTypeImpl.get("SAND");

    SoundType SNOW = SoundTypeImpl.get("SNOW");

    SoundType POWDER_SNOW = SoundTypeImpl.get("POWDER_SNOW");

    SoundType LADDER = SoundTypeImpl.get("LADDER");

    SoundType ANVIL = SoundTypeImpl.get("ANVIL");

    SoundType SLIME_BLOCK = SoundTypeImpl.get("SLIME_BLOCK");

    SoundType HONEY_BLOCK = SoundTypeImpl.get("HONEY_BLOCK");

    SoundType WET_GRASS = SoundTypeImpl.get("WET_GRASS");

    SoundType CORAL_BLOCK = SoundTypeImpl.get("CORAL_BLOCK");

    SoundType BAMBOO = SoundTypeImpl.get("BAMBOO");

    SoundType BAMBOO_SAPLING = SoundTypeImpl.get("BAMBOO_SAPLING");

    SoundType SCAFFOLDING = SoundTypeImpl.get("SCAFFOLDING");

    SoundType SWEET_BERRY_BUSH = SoundTypeImpl.get("SWEET_BERRY_BUSH");

    SoundType CROP = SoundTypeImpl.get("CROP");

    SoundType HARD_CROP = SoundTypeImpl.get("HARD_CROP");

    SoundType VINE = SoundTypeImpl.get("VINE");

    SoundType NETHER_WART = SoundTypeImpl.get("NETHER_WART");

    SoundType LANTERN = SoundTypeImpl.get("LANTERN");

    SoundType STEM = SoundTypeImpl.get("STEM");

    SoundType NYLIUM = SoundTypeImpl.get("NYLIUM");

    SoundType FUNGUS = SoundTypeImpl.get("FUNGUS");

    SoundType ROOTS = SoundTypeImpl.get("ROOTS");

    SoundType SHROOMLIGHT = SoundTypeImpl.get("SHROOMLIGHT");

    SoundType WEEPING_VINES = SoundTypeImpl.get("WEEPING_VINES");

    SoundType TWISTING_VINES = SoundTypeImpl.get("TWISTING_VINES");

    SoundType SOUL_SAND = SoundTypeImpl.get("SOUL_SAND");

    SoundType SOUL_SOIL = SoundTypeImpl.get("SOUL_SOIL");

    SoundType BASALT = SoundTypeImpl.get("BASALT");

    SoundType WART_BLOCK = SoundTypeImpl.get("WART_BLOCK");

    SoundType NETHERRACK = SoundTypeImpl.get("NETHERRACK");

    SoundType NETHER_BRICKS = SoundTypeImpl.get("NETHER_BRICKS");

    SoundType NETHER_SPROUTS = SoundTypeImpl.get("NETHER_SPROUTS");

    SoundType NETHER_ORE = SoundTypeImpl.get("NETHER_ORE");

    SoundType BONE_BLOCK = SoundTypeImpl.get("BONE_BLOCK");

    SoundType NETHERITE_BLOCK = SoundTypeImpl.get("NETHERITE_BLOCK");

    SoundType ANCIENT_DEBRIS = SoundTypeImpl.get("ANCIENT_DEBRIS");

    SoundType LODESTONE = SoundTypeImpl.get("LODESTONE");

    SoundType CHAIN = SoundTypeImpl.get("CHAIN");

    SoundType NETHER_GOLD_ORE = SoundTypeImpl.get("NETHER_GOLD_ORE");

    SoundType GILDED_BLACKSTONE = SoundTypeImpl.get("GILDED_BLACKSTONE");

    SoundType CANDLE = SoundTypeImpl.get("CANDLE");

    SoundType AMETHYST = SoundTypeImpl.get("AMETHYST");

    SoundType AMETHYST_CLUSTER = SoundTypeImpl.get("AMETHYST_CLUSTER");

    SoundType SMALL_AMETHYST_BUD = SoundTypeImpl.get("SMALL_AMETHYST_BUD");

    SoundType MEDIUM_AMETHYST_BUD = SoundTypeImpl.get("MEDIUM_AMETHYST_BUD");

    SoundType LARGE_AMETHYST_BUD = SoundTypeImpl.get("LARGE_AMETHYST_BUD");

    SoundType TUFF = SoundTypeImpl.get("TUFF");

    SoundType CALCITE = SoundTypeImpl.get("CALCITE");

    SoundType DRIPSTONE_BLOCK = SoundTypeImpl.get("DRIPSTONE_BLOCK");

    SoundType POINTED_DRIPSTONE = SoundTypeImpl.get("POINTED_DRIPSTONE");

    SoundType COPPER = SoundTypeImpl.get("COPPER");

    SoundType CAVE_VINES = SoundTypeImpl.get("CAVE_VINES");

    SoundType SPORE_BLOSSOM = SoundTypeImpl.get("SPORE_BLOSSOM");

    SoundType AZALEA = SoundTypeImpl.get("AZALEA");

    SoundType FLOWERING_AZALEA = SoundTypeImpl.get("FLOWERING_AZALEA");

    SoundType MOSS_CARPET = SoundTypeImpl.get("MOSS_CARPET");

    SoundType MOSS = SoundTypeImpl.get("MOSS");

    SoundType BIG_DRIPLEAF = SoundTypeImpl.get("BIG_DRIPLEAF");

    SoundType SMALL_DRIPLEAF = SoundTypeImpl.get("SMALL_DRIPLEAF");

    SoundType ROOTED_DIRT = SoundTypeImpl.get("ROOTED_DIRT");

    SoundType HANGING_ROOTS = SoundTypeImpl.get("HANGING_ROOTS");

    SoundType AZALEA_LEAVES = SoundTypeImpl.get("AZALEA_LEAVES");

    SoundType SCULK_SENSOR = SoundTypeImpl.get("SCULK_SENSOR");

    SoundType GLOW_LICHEN = SoundTypeImpl.get("GLOW_LICHEN");

    SoundType DEEPSLATE = SoundTypeImpl.get("DEEPSLATE");

    SoundType DEEPSLATE_BRICKS = SoundTypeImpl.get("DEEPSLATE_BRICKS");

    SoundType DEEPSLATE_TILES = SoundTypeImpl.get("DEEPSLATE_TILES");

    SoundType POLISHED_DEEPSLATE = SoundTypeImpl.get("POLISHED_DEEPSLATE");
}
